global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'finance-tracker-backend'
    static_configs:
      - targets: ['backend:5050']
    metrics_path: /metrics
    scheme: http
    scrape_interval: 15s

  # cAdvisor for Docker container monitoring
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: /metrics
    scheme: http
    scrape_interval: 15s